[tool.poetry]
name = "hashsearch"
version = "0.1.0"
description = "Search hashes quickly before cracking them"
authors = ["Bee"]

[tool.poetry.dependencies]
python = "^3.5"
click = "^7.1.2"
google-search = "^1.0.2"
appdirs = "^1.4.4"
toml = "^0.10.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
